spring:
  application:
    name: todo-api-gateway
  zipkin:
    baseUrl: http://zipkin-server:9411

server:
  port: 8765

eureka:
  client:
      serviceUrl:
          defaultZone: http://todo-service-registry:8761/eureka